'use client';
import { useQuery } from '@tanstack/react-query';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { api, EventItem, formatDate } from '@/lib/api';
import { Empty, ErrorMessage } from '@/components/ui';
type Dashboard={eventCount:number;deliveryCount:number;delivered:number;failed:number;successRate:number;recentEvents:EventItem[];recentFailures:Array<{id:string;lastError?:string;event:{type:string};endpoint:{name:string}}>};
export default function Overview(){const {projectId}=useParams<{projectId:string}>();const query=useQuery({queryKey:['dashboard',projectId],queryFn:()=>api<Dashboard>(`/projects/${projectId}/dashboard`)});const d=query.data;return <div className="stack"><ErrorMessage error={query.error}/><div className="grid grid-4"><div className="panel stat"><span>Events</span><strong>{d?.eventCount ?? '—'}</strong></div><div className="panel stat"><span>Deliveries</span><strong>{d?.deliveryCount ?? '—'}</strong></div><div className="panel stat"><span>Success rate</span><strong>{d ? `${d.successRate}%` : '—'}</strong></div><div className="panel stat"><span>Failed</span><strong style={{color:'var(--red)'}}>{d?.failed ?? '—'}</strong></div></div><div className="grid grid-2"><section className="panel"><h2 className="section-title">Recent events</h2>{!d?.recentEvents.length?<Empty title="No events" detail="Publish an event to see it here."/>:<div className="stack">{d.recentEvents.map(e=><Link className="split" href={`/projects/${projectId}/events/${e.id}`} key={e.id}><span><strong>{e.type}</strong><small className="muted" style={{display:'block'}}>{formatDate(e.createdAt)}</small></span><span className="muted">{e._count?.deliveries} deliveries →</span></Link>)}</div>}</section><section className="panel"><h2 className="section-title">Recent failures</h2>{!d?.recentFailures.length?<Empty title="All clear" detail="There are no failed deliveries."/>:<div className="stack">{d.recentFailures.map(f=><Link className="split" href={`/deliveries/${f.id}`} key={f.id}><span><strong>{f.event.type}</strong><small className="muted" style={{display:'block'}}>{f.endpoint.name}</small></span><span style={{color:'var(--red)'}}>{f.lastError ?? 'Failed'} →</span></Link>)}</div>}</section></div></div>}

